name: build-html-docs
on: [push]
jobs:
  checkout-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8

      - name: Install the project
        run: uv sync --locked

      - name: Build the website
        run: uv run make html

      -
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: echo "$DEPLOY_KEY" > github@deploy

      - run: chmod 600 github@deploy

      #- run: cat github@deploy

      - name: publish the website
        run: rsync -a --delete-excluded -e "$SSH_COMMAND" _build/html/ www-user@digigaia.org:www/digitalgaia/
        env:
          SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i github@deploy"
